# Generated by Django 2.0.2 on 2018-03-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uprofile',
            name='ucellphone',
            field=models.CharField(max_length=11, null=True, unique=True, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='uprofile',
            name='uname',
            field=models.CharField(max_length=32, null=True, verbose_name='用户姓名'),
        ),
    ]
