# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 15:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News_center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=50, verbose_name='新闻标题')),
                ('news_time', models.CharField(max_length=30, verbose_name='新闻时间')),
                ('news_image', models.ImageField(upload_to='', verbose_name='新闻照片')),
                ('news_content', models.TextField(max_length=3072, verbose_name='新闻内容')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='编辑时间')),
                ('is_delete', models.BooleanField(verbose_name=False)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='编辑人')),
            ],
            options={
                'verbose_name': '新闻中心',
                'verbose_name_plural': '新闻中心',
            },
        ),
        migrations.CreateModel(
            name='Recruitment_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_area', models.CharField(max_length=20, verbose_name='工作地区')),
                ('position_name', models.CharField(max_length=20, verbose_name='工作岗位')),
                ('number', models.IntegerField(verbose_name='招聘人数')),
                ('experience', models.CharField(max_length=20, verbose_name='工作经验')),
                ('necessary_skills', models.TextField(max_length=1024, verbose_name='技能要求')),
                ('position_salary', models.CharField(max_length=5, verbose_name='薪资待遇')),
                ('job_responsibilities', models.TextField(max_length=1024, verbose_name='岗位职责')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='编辑时间')),
                ('is_delete', models.BooleanField(verbose_name=False)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='编辑人')),
            ],
            options={
                'verbose_name': '招聘信息',
                'verbose_name_plural': '招聘信息',
            },
        ),
    ]
