# Generated by Django 2.0.2 on 2018-03-23 11:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News_center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=50, verbose_name='新闻标题')),
                ('display_area', models.IntegerField(choices=[(1, '重磅新闻，页面最上'), (2, '次要新闻，页面中间')], default=2)),
                ('news_time', models.DateTimeField(verbose_name='新闻时间')),
                ('news_image1', models.ImageField(blank=True, default='', null=True, upload_to='index/news_pic', verbose_name='新闻照片1')),
                ('news_image2', models.ImageField(blank=True, default='', null=True, upload_to='index/news_pic', verbose_name='新闻照片2')),
                ('news_image3', models.ImageField(blank=True, default='', null=True, upload_to='index/news_pic', verbose_name='新闻照片3')),
                ('news_image4', models.ImageField(blank=True, default='', null=True, upload_to='index/news_pic', verbose_name='新闻照片4')),
                ('news_image5', models.ImageField(blank=True, default='', null=True, upload_to='index/news_pic', verbose_name='新闻照片5')),
                ('news_content', models.TextField(max_length=3072, verbose_name='新闻内容')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='编辑时间')),
                ('is_delete', models.BooleanField(choices=[(False, '保存'), (True, '删除')], default=False, verbose_name='逻辑删除')),
                ('created_by', models.ForeignKey(on_delete=True, to=settings.AUTH_USER_MODEL, verbose_name='编辑人')),
            ],
            options={
                'verbose_name': '新闻中心',
                'verbose_name_plural': '新闻中心',
                'ordering': ('created_time',),
            },
        ),
        migrations.CreateModel(
            name='Recruitment_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_area', models.CharField(max_length=20, verbose_name='工作地区')),
                ('position_name', models.CharField(max_length=20, verbose_name='工作岗位')),
                ('number', models.IntegerField(verbose_name='招聘人数')),
                ('experience', models.CharField(max_length=20, verbose_name='工作经验')),
                ('necessary_skills', models.TextField(max_length=1024, verbose_name='技能要求')),
                ('job_responsibilities', models.TextField(max_length=1024, verbose_name='岗位职责')),
                ('position_salary', models.CharField(max_length=5, verbose_name='薪资待遇')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='编辑时间')),
                ('is_delete', models.BooleanField(choices=[(False, '保存'), (True, '删除')], default=False, verbose_name='逻辑删除')),
                ('created_by', models.ForeignKey(on_delete=True, to=settings.AUTH_USER_MODEL, verbose_name='编辑人')),
            ],
            options={
                'verbose_name': '招聘信息',
                'verbose_name_plural': '招聘信息',
                'ordering': ('created_time',),
            },
        ),
    ]
