# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 15:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_center',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='编辑人'),
        ),
        migrations.AlterField(
            model_name='news_center',
            name='is_delete',
            field=models.BooleanField(choices=[(False, '保存'), (True, '删除')], default=False, verbose_name='逻辑删除'),
        ),
        migrations.AlterField(
            model_name='recruitment_info',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='编辑人'),
        ),
        migrations.AlterField(
            model_name='recruitment_info',
            name='is_delete',
            field=models.BooleanField(choices=[(False, '保存'), (True, '删除')], default=False, verbose_name='逻辑删除'),
        ),
    ]
