# Generated by Django 2.0.2 on 2018-04-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news_center',
            name='news_content',
        ),
        migrations.AddField(
            model_name='news_center',
            name='news_content1',
            field=models.TextField(blank=True, default='', max_length=1024, null=True, verbose_name='新闻内容段落1'),
        ),
        migrations.AddField(
            model_name='news_center',
            name='news_content10',
            field=models.TextField(blank=True, default='', max_length=1024, null=True, verbose_name='新闻内容段落10'),
        ),
        migrations.AddField(
            model_name='news_center',
            name='news_content11',
            field=models.TextField(blank=True, default='', max_length=1024, null=True, verbose_name='新闻内容段落11'),
        ),
        migrations.AddField(
            model_name='news_center',
            name='news_content12',
            field=models.TextField(blank=True, default='', max_length=1024, null=True, verbose_name='新闻内容段落12'),
        ),
        migrations.AddField(
            model_name='news_center',
            name='news_content13',
            field=models.TextField(blank=True, default='', max_length=1024, null=True, verbose_name='新闻内容段落13'),
        ),
        migrations.AddField(
            model_name='news_center',
            name='news_content14',
            field=models.TextField(blank=True, default='', max_length=1024, null=True, verbose_name='新闻内容段落14'),
        ),
        migrations.AddField(
            model_name='news_center',
            name='news_content15',
            field=models.TextField(blank=True, default='', max_length=1024, null=True, verbose_name='新闻内容段落15'),
        ),
        migrations.AddField(
            model_name='news_center',
            name='news_content16',
            field=models.TextField(blank=True, default='', max_length=1024, null=True, verbose_name='新闻内容段落16'),
        ),
        migrations.AddField(
            model_name='news_center',
            name='news_content17',
            field=models.TextField(blank=True, default='', max_length=1024, null=True, verbose_name='新闻内容段落17'),
        ),
        migrations.AddField(
            model_name='news_center',
            name='news_content18',
            field=models.TextField(blank=True, default='', max_length=1024, null=True, verbose_name='新闻内容段落18'),
        ),
        migrations.AddField(
            model_name='news_center',
            name='news_content19',
            field=models.TextField(blank=True, default='', max_length=1024, null=True, verbose_name='新闻内容段落19'),
        ),
        migrations.AddField(
            model_name='news_center',
            name='news_content2',
            field=models.TextField(blank=True, default='', max_length=1024, null=True, verbose_name='新闻内容段落2'),
        ),
        migrations.AddField(
            model_name='news_center',
            name='news_content20',
            field=models.TextField(blank=True, default='', max_length=1024, null=True, verbose_name='新闻内容段落20'),
        ),
        migrations.AddField(
            model_name='news_center',
            name='news_content3',
            field=models.TextField(blank=True, default='', max_length=1024, null=True, verbose_name='新闻内容段落3'),
        ),
        migrations.AddField(
            model_name='news_center',
            name='news_content4',
            field=models.TextField(blank=True, default='', max_length=1024, null=True, verbose_name='新闻内容段落4'),
        ),
        migrations.AddField(
            model_name='news_center',
            name='news_content5',
            field=models.TextField(blank=True, default='', max_length=1024, null=True, verbose_name='新闻内容段落5'),
        ),
        migrations.AddField(
            model_name='news_center',
            name='news_content6',
            field=models.TextField(blank=True, default='', max_length=1024, null=True, verbose_name='新闻内容段落6'),
        ),
        migrations.AddField(
            model_name='news_center',
            name='news_content7',
            field=models.TextField(blank=True, default='', max_length=1024, null=True, verbose_name='新闻内容段落7'),
        ),
        migrations.AddField(
            model_name='news_center',
            name='news_content8',
            field=models.TextField(blank=True, default='', max_length=1024, null=True, verbose_name='新闻内容段落8'),
        ),
        migrations.AddField(
            model_name='news_center',
            name='news_content9',
            field=models.TextField(blank=True, default='', max_length=1024, null=True, verbose_name='新闻内容段落9'),
        ),
        migrations.AddField(
            model_name='news_center',
            name='news_image10',
            field=models.ImageField(blank=True, default='', null=True, upload_to='index/news_pic', verbose_name='新闻图片段落10下'),
        ),
        migrations.AddField(
            model_name='news_center',
            name='news_image11',
            field=models.ImageField(blank=True, default='', null=True, upload_to='index/news_pic', verbose_name='新闻图片段落11下'),
        ),
        migrations.AddField(
            model_name='news_center',
            name='news_image12',
            field=models.ImageField(blank=True, default='', null=True, upload_to='index/news_pic', verbose_name='新闻图片段落12下'),
        ),
        migrations.AddField(
            model_name='news_center',
            name='news_image13',
            field=models.ImageField(blank=True, default='', null=True, upload_to='index/news_pic', verbose_name='新闻图片段落13下'),
        ),
        migrations.AddField(
            model_name='news_center',
            name='news_image14',
            field=models.ImageField(blank=True, default='', null=True, upload_to='index/news_pic', verbose_name='新闻图片段落14下'),
        ),
        migrations.AddField(
            model_name='news_center',
            name='news_image15',
            field=models.ImageField(blank=True, default='', null=True, upload_to='index/news_pic', verbose_name='新闻图片段落15下'),
        ),
        migrations.AddField(
            model_name='news_center',
            name='news_image16',
            field=models.ImageField(blank=True, default='', null=True, upload_to='index/news_pic', verbose_name='新闻图片段落16下'),
        ),
        migrations.AddField(
            model_name='news_center',
            name='news_image17',
            field=models.ImageField(blank=True, default='', null=True, upload_to='index/news_pic', verbose_name='新闻图片段落17下'),
        ),
        migrations.AddField(
            model_name='news_center',
            name='news_image18',
            field=models.ImageField(blank=True, default='', null=True, upload_to='index/news_pic', verbose_name='新闻图片段落18下'),
        ),
        migrations.AddField(
            model_name='news_center',
            name='news_image19',
            field=models.ImageField(blank=True, default='', null=True, upload_to='index/news_pic', verbose_name='新闻图片段落19下'),
        ),
        migrations.AddField(
            model_name='news_center',
            name='news_image20',
            field=models.ImageField(blank=True, default='', null=True, upload_to='index/news_pic', verbose_name='新闻图片段落20下'),
        ),
        migrations.AddField(
            model_name='news_center',
            name='news_image6',
            field=models.ImageField(blank=True, default='', null=True, upload_to='index/news_pic', verbose_name='新闻图片段落6下'),
        ),
        migrations.AddField(
            model_name='news_center',
            name='news_image7',
            field=models.ImageField(blank=True, default='', null=True, upload_to='index/news_pic', verbose_name='新闻图片段落7下'),
        ),
        migrations.AddField(
            model_name='news_center',
            name='news_image8',
            field=models.ImageField(blank=True, default='', null=True, upload_to='index/news_pic', verbose_name='新闻图片段落8下'),
        ),
        migrations.AddField(
            model_name='news_center',
            name='news_image9',
            field=models.ImageField(blank=True, default='', null=True, upload_to='index/news_pic', verbose_name='新闻图片段落9下'),
        ),
        migrations.AlterField(
            model_name='news_center',
            name='display_area',
            field=models.IntegerField(choices=[(1, '重磅新闻，页面最上'), (2, '次要新闻，页面中间'), (3, '其他新闻')], default=2),
        ),
        migrations.AlterField(
            model_name='news_center',
            name='news_image1',
            field=models.ImageField(blank=True, default='', null=True, upload_to='index/news_pic', verbose_name='新闻图片段落1下'),
        ),
        migrations.AlterField(
            model_name='news_center',
            name='news_image2',
            field=models.ImageField(blank=True, default='', null=True, upload_to='index/news_pic', verbose_name='新闻图片段落2下'),
        ),
        migrations.AlterField(
            model_name='news_center',
            name='news_image3',
            field=models.ImageField(blank=True, default='', null=True, upload_to='index/news_pic', verbose_name='新闻图片段落3下'),
        ),
        migrations.AlterField(
            model_name='news_center',
            name='news_image4',
            field=models.ImageField(blank=True, default='', null=True, upload_to='index/news_pic', verbose_name='新闻图片段落4下'),
        ),
        migrations.AlterField(
            model_name='news_center',
            name='news_image5',
            field=models.ImageField(blank=True, default='', null=True, upload_to='index/news_pic', verbose_name='新闻图片段落5下'),
        ),
    ]
