# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20180112_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_center',
            name='news_time',
            field=models.DateTimeField(verbose_name='新闻时间'),
        ),
    ]
